language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
script:
- "./travis-build.sh --quiet verify"
env:
  global:
  - secure: "XpcjFyyy/fIDS5YHSYjnG6OOoIKmcFokPCsrtAdXNUnRREsUAeMtNJA2tBbmQvLhBv4tkxlOB3bu4ZDAWCYQB5o2nt0ZD7K3JSfRSwbw3TitfxtNuwBVgZsK4e+J28OWl/kVTysFlKCK9wF5RCsnJTPlsNBktp3xM3timTeoTO/LhztpeBlFvALhS8RkFDEpHIoyQ6xXy/zY3AcnHLaYvFvkIEb2vGWIQ6ptYRo/KylQ7A+nIPuhF1bBbpEz/CCqJjUC8ZCQ8/rBcTYYf7RgUoH6FJ4N9H720J4Dpa3ngUzPqMEzPNW903WZeXa65bQc0oQ/JmaD8KBn/AvYh3XtQoyulNIKFY76EZJOyHUhl4mzK3QkMcpJ9TE2U9RVixNAxL69qgP80MZ/Y/+vOy3jMdOc1VQZRFTK0ZkZw6wwbY75Xaeo8mXpyU58IJG1X7bl6VT+jaSxhfqhyOSy3ZorUIK5399HFPU14xpQNzlydvRz+Q7YIXHuvJmJH7JI9rF/jN8gFIG6zOHXvD6NmBwbK3tx3if8UrgAeTblI4A3JNKmHWUwm/3E4R5fEdNBHm5Rulr7G0gHqdG1NvSJNCwMb9UngNNCBGBKcHl3f933IYt+xkOX1t1+iTM5VOr6AkdW+G9qSW/dXWQa464QOeJrYc743FZtPWwVJWW75ZAOoYA="
deploy:
- provider: script
  script: bash deploy.sh $AZURE_WA_PASSWORD dev
  on: master
- provider: script
  script: bash deploy.sh $AZURE_WA_PASSWORD staging
  on: staging
- provider: script
  script: bash deploy.sh $AZURE_WA_PASSWORD prod
  on: production
