language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
script:
- "./travis-build.sh --quiet verify"
deploy:
- provider: azure_web_apps
  username:
    secure: "YLZdwC766CGQUT03uh88tF38KhEwqhA3ud0vNKUz4V4OOeLzdQ+Hj2WkTZ9iH+KVPGYTnvjqatanGiK9f2Dw2xk5mXS4dbSus2x00n06PNWx3LDoIGEbLmfj50B1bGJCxgg0UjPEtp004sMhihrn6wuuxKyCVHAOE7t4kb2yD342KXUTZz7dOoeRctW3mTXmulcJmZLliDYGBVcaYd4op572rzUdflfEcKDKt9KZ1YnpBuvn8UaMGwmYt6Xf7dDce1/nlSJixd/6MduYchSvcpIFWD9ewNZO//PL2A7jxxtPK8VcTpkndVdcZuQ+tuEohQ0yXPdMon/SUgdNTvunlxz3g/TwImD4O3cnd9Ac4UZ4g2MiG0fCF8Xh8i+F1ubb+8QEc1WqX8TEvtPfu+woH20lEvCSIoe5u/Co1SPK/cwmPEZ9qX6SkNo7cPg80gTE0+gmeMou3Z05ebUi4cUgBrUCmxl3blvHGETddftV6n2IYcc72qkcWpfXmhKPb0ZZTHmoZRMz0OPvMlftox+P/Otu40zIGdTN6YQrUr+3oFxLn2IhQhCppiUXNe9myrGsHLMbIxNBRKjtMjFs1CoxO+3XjiAus69TBdD7rkzHn7JlsAX0ipoS1gTVyXX3NnNYRu6I/8p0VpreAg4oEe8rrCsJcQFqe7zVr7Iy+Uc7ELk="
  password:
    secure: "ZFIQI05qbQzVmoKsDIllTVjcEMZ1ERZKvMkuL3vUT7UnlAvjf8v65v3cPomeCkjp47pyLNcXZukIDK3MY1Mlsc7KFYnpN1fFCTpRHfoersFDvLXigAf7cZ1BNCpqTg+M4HuqhpKCu01jRAKVvrBtCoyXsOwKF1fhhQx2Wh2NwxRS/pG/z4v+FXcpOMpmb6og7vWFoo1SCvU9xO4OyDGw52I0n0PEFACNGz2wNJgNs0g4LAMNW1tkrXTGjwcGxwhSRRsdy1NoBvSqog2DvbL/ZHG0okyUbifRTuUyM0qxZ9XGYeVMDykBbifNWQg99avF7xpAAxHcv1UFVDpX5IAb8DGfQijK/SzWubVVuAbYW4Fl7bcVT8ELpsMqH2vPFlohSgkiwKEPf/MqoUrqHspsZkQ9JnNdC95Pmx8jB1IcNUiYw84RiCHJZ8ISnegSyW8Wc8lamjia6WE8icJzLS30vFxEH+nULIe3Q8cadpOikc+a/FAw0R0ABll2eZRYHYHUVYC/ad4YAFqtQspprS7K5oNFy3ZvudxGLDbmq3Y6PA+mTzHugIPkWkydfqw+UDdzDoZ229jH2p014dNAEUxbgOrDpcoiyVEQGCKnR9dgyM5sIU1f8/sDVkovFqrsEF9Rq1jTls9IEeMXH9ftIWptjijF8ueTEayCfvYGub4zvaY="
  site: bat-dev-search-and-compare-ui-app
  on: master
- provider: azure_web_apps
  site: bat-staging-search-and-compare-ui-app
  on: staging
- provider: azure_web_apps
  site: bat-prod-search-and-compare-ui-app
  on: production