language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
script:
- "./travis-build.sh --quiet verify"
deploy:
- provider: azure_web_apps
  username: govuk-dfe-bat-deployment-user
  password:
    secure: "CNb3wmmK+LhUK4nE3mEWn4aV9KZjpsVm80F/FvCz5QWdEy0fq90GY2tszc7vEsA560kar8Z7VpFuNKeNq4bT+wuug6YYqIVY8Wu5s3l1040p3BrujKuzRFGaMx1UPNsQOoeAuAx6mL8E6hhTobYXXJLJk/gnNr4Y8huDEF5JxvI9Iloc6UQ0m+Ht/I9TSsHxBKIDq9sJ3ByBpPtTX2tM4DaWI43PdEfbQYvALSRmfbcng0+FctGZyor+ARLYOhn7m4Av3rECw34uUEQlTo4IXFa4fF2Op/C3Rb3mvEJrTDmAuZX1GYPd97pVaNqIQJ9OnSM5gUXapd0IF7pu6tJy8K/AmrZOVmfEPzXjnRiL0jJOlLGzL/xU3eBYhNvNfxSrWF0nQxys8WedytQGO+fgYjm9qtMMDpAsMadywcaxFaS+pdsi1TOLhmKhUgFUbwoCln5KeSuiclJEhU7+GO8ATayirId1k98luiZNhy8Ky2g45P0wFohtEvbDRHZZHfLzyu1JxDOSoxPCiCNfH4+uVT+hYL9/qNI5x54rtTCYX0iCfp52iJXJrW97A3cpyygKUttgkXE9EhJVyOk2nrEHFPl/8O/Vb7KMlOxQJNO/IprUGzNKMitqaIs/FARRC/4YjDMGeK9b7Fafwcp/SfephfbTBqU+xRGMeVwhtXn4BdY="
  site: bat-dev-search-and-compare-ui-app
  on: master
- provider: azure_web_apps
  username: govuk-dfe-bat-deployment-user
  password:
    secure: "CNb3wmmK+LhUK4nE3mEWn4aV9KZjpsVm80F/FvCz5QWdEy0fq90GY2tszc7vEsA560kar8Z7VpFuNKeNq4bT+wuug6YYqIVY8Wu5s3l1040p3BrujKuzRFGaMx1UPNsQOoeAuAx6mL8E6hhTobYXXJLJk/gnNr4Y8huDEF5JxvI9Iloc6UQ0m+Ht/I9TSsHxBKIDq9sJ3ByBpPtTX2tM4DaWI43PdEfbQYvALSRmfbcng0+FctGZyor+ARLYOhn7m4Av3rECw34uUEQlTo4IXFa4fF2Op/C3Rb3mvEJrTDmAuZX1GYPd97pVaNqIQJ9OnSM5gUXapd0IF7pu6tJy8K/AmrZOVmfEPzXjnRiL0jJOlLGzL/xU3eBYhNvNfxSrWF0nQxys8WedytQGO+fgYjm9qtMMDpAsMadywcaxFaS+pdsi1TOLhmKhUgFUbwoCln5KeSuiclJEhU7+GO8ATayirId1k98luiZNhy8Ky2g45P0wFohtEvbDRHZZHfLzyu1JxDOSoxPCiCNfH4+uVT+hYL9/qNI5x54rtTCYX0iCfp52iJXJrW97A3cpyygKUttgkXE9EhJVyOk2nrEHFPl/8O/Vb7KMlOxQJNO/IprUGzNKMitqaIs/FARRC/4YjDMGeK9b7Fafwcp/SfephfbTBqU+xRGMeVwhtXn4BdY="
  site: bat-staging-search-and-compare-ui-app
  on: staging
- provider: azure_web_apps
  username: govuk-dfe-bat-deployment-user
  password:
    secure: "CNb3wmmK+LhUK4nE3mEWn4aV9KZjpsVm80F/FvCz5QWdEy0fq90GY2tszc7vEsA560kar8Z7VpFuNKeNq4bT+wuug6YYqIVY8Wu5s3l1040p3BrujKuzRFGaMx1UPNsQOoeAuAx6mL8E6hhTobYXXJLJk/gnNr4Y8huDEF5JxvI9Iloc6UQ0m+Ht/I9TSsHxBKIDq9sJ3ByBpPtTX2tM4DaWI43PdEfbQYvALSRmfbcng0+FctGZyor+ARLYOhn7m4Av3rECw34uUEQlTo4IXFa4fF2Op/C3Rb3mvEJrTDmAuZX1GYPd97pVaNqIQJ9OnSM5gUXapd0IF7pu6tJy8K/AmrZOVmfEPzXjnRiL0jJOlLGzL/xU3eBYhNvNfxSrWF0nQxys8WedytQGO+fgYjm9qtMMDpAsMadywcaxFaS+pdsi1TOLhmKhUgFUbwoCln5KeSuiclJEhU7+GO8ATayirId1k98luiZNhy8Ky2g45P0wFohtEvbDRHZZHfLzyu1JxDOSoxPCiCNfH4+uVT+hYL9/qNI5x54rtTCYX0iCfp52iJXJrW97A3cpyygKUttgkXE9EhJVyOk2nrEHFPl/8O/Vb7KMlOxQJNO/IprUGzNKMitqaIs/FARRC/4YjDMGeK9b7Fafwcp/SfephfbTBqU+xRGMeVwhtXn4BdY="
  site: bat-prod-search-and-compare-ui-app
  on: production