matrix:
  include:
    - language: csharp
      dist: trusty
      sudo: required
      mono: none
      dotnet: 2.1
      script:
        - "./travis-build.sh --quiet verify"
      deploy:
        - provider: script
          script: git fetch --unshallow && git remote add deploy https://$bat-dev-search-and-compare-ui-app:$APP_CREDENTIALS_DEV_PWD@bat-dev-search-and-compare-ui-app.scm.azurewebsites.net:443/bat-dev-search-and-compare-ui-app.git && git push --force deploy HEAD:refs/heads/master
          on: master
        - provider: script
          script: git fetch --unshallow && git remote add deploy https://$bat-dev-search-and-compare-ui-app:$APP_CREDENTIALS_STAGING_PWD@bat-staging-search-and-compare-ui-app.scm.azurewebsites.net:443/bat-staging-search-and-compare-ui-app.git && git push --force deploy HEAD:refs/heads/master
          on: staging
        - provider: script
          script: git fetch --unshallow && git remote add deploy https://$bat-prod-2018-search-and-compare-ui-app:$APP_CREDENTIALS_PROD_PWD@bat-prod-2018-search-and-compare-ui-app.scm.azurewebsites.net:443/bat-prod-2018-search-and-compare-ui-app.git && git push --force deploy HEAD:refs/heads/master
          on: production
        - provider: script
          skip_cleanup: true
          script: chmod +x ./travis-nuget-deploy.sh && ./travis-nuget-deploy.sh $NUGET_API_KEY
            $NUGET_SOURCE
          on:
            all_branches: true
    - language: node_js
      node_js:
        - 10.8
      cache:
        directories:
          - "~/.npm"
          - "~/.cache"
        override:
          - npm ci
      before_script:
        - cd src
        - npm ci
      script:
        - npm test
        - cd ..
env:
  global:
    - secure: MoOTHg1BuQF6ERP2uyGXSr5ADwOdMfg3q0HpxrKcI7T04OUpodmDN05gW3WlYTQ20iiT+SkZRsxOzL9fpIoQvXNaHQfQ+589nmxla8ZcpwAZvp29LEXuYq3K1BfqiGOGAkwZlxGKqfWjK6ttGiMCXufDAkMknx3PlL8OvdGLQkyYby2NcTMOAZsf4Rjc0UKNjUS7OD213Ej+HE1MQUgAz9S128srfGmWoPMSokXYJcEpMhzJbS2deZ1PN1kRw0Y60HiaT6judePWT6YHadqgGZlSF+B8zd62eGu04D32B8otvK4VpyjKmAdlNTgL+wiNhiLtSsaczpX65WY3Zt3neAb+msggATpYF8lvVjwdeyZv5RnxfQJIAi6Ohapqa1yRYxuSfPfgEHzbjNKnjjh9u+NTLoYNWy1cA0By2fxdK6LMV+2Th1jt7SMVAo007NSb/q1R6tLo8BE4r2RA2m7oXpP95CLboI9+Vs6kxVZEoPxKS8VWgfNSc3Bt+QAoitygChVMzS6dXzYUfLmwh/v96Xi8jOq0zEAgT23sxwflODMsZe6fKdS+GAy9pxfGLxJGN2vkyzhVqQ6asD/dcIFYr+6bnAheCqSxQ5xoy8kLTy86bBYclDDvLPxt+j0BTIIk9wEAzkDvvIiPnxnQ1iiFgxEAodGrs5/6ZVX0Qc3hUis=
    - NUGET_SOURCE=https://www.nuget.org
    - secure: smCYdgwSuPOlGvtFntqRjAgylc+MRP/ITJqC1ClP+X8ed/zlM5Fgda7OFAsIZBGvmD7c5g2sft/WXEjIeBZ8W7Oz9v975RG3sdt+g8VYQfB4oscyvHzteAbIDVbnoPEPiPKHAp+8oG3yVmzbxVsEcxlR8kN2dgbbHRlE1F82lT7e78CST1FvKV+wNemVC4cITBLR8SFPxy35I8FL8d7R7zQUGeeKqGenK72i9YvE9Zb3QAEe49HZ1JzdZyAQfxQLCYgip3h+e7Jp8TnnJwHDIrMd6VYjPEnDkfgwl1AqLw1jSbALit0ScfieQy0tZt+FlugQbzgv5gRoFQO48WPpk0Q90Xr9a4IUviiCMowGxUvZYwOJxQzz9cDeC7hjc7YH8z2IDDIXtIcDdMjiQIdY+u4hqWXkoJ5O7flB7QzBTI/a5TVuftgMW3G3Vr3bw6wMswTmFruxnanLhbVCgZ0xy0H7O/1M0KtdhLEAvEEmwQF/tje+yNhJJhiXz/S2yWQI62U6nkWbDXuz6q/U0S6Y6j46hU/5m2xoobo9MA017FSppGb0RF3VzYp3a8ez5PHe+fHQwSeQo168j5dy6tgLWRspD8fNEBfe/knSVZltQdNq74/xBGtytrjfQcl3lltaVrwD6uNRISPzK27YAVtzuNnIeqWhQJJonA0jglu6/w8=
        # AZURE_WA_PASSWORD
  - secure: Jevjau9bkjgarHgHLBmptIRIysFdMWYaYjMQdJNd61GS1hDIZqwdIr843hfnvEbgRIJRa/8oCpW/2iasjC9qQ6ZZuM8Km8Ay75qWEpaWRWCddq5fSKtIb6pnzRhC0NsviMVRluJvlQYA5b4NnOosS26913ylk1PKgfEcV5s/nxb7UxiEvoSeCjLxhOq1SXhM8SS2D8kjXZz7xYEigTGzNc4e6ZMj44b4O1sDZAQPxpKc6ELAi8ncZXZax5ZuuUsUMKT+qwo1JbDcJE2CwUXgWR/8yUFWNVDkjM0N0+z2m3wEJhOcYJV0q7X2YavI920KAp4iAbOLqRXd/uaaxW5AorzJFP4FyH2fBtYsISGZUeLXp20qgeJoz3XxZJP4LjCttXGNU2CTNpupuqCudJaT0D4HIGU4GyOnki24sRbnbeFjRstx1/+VLoKNndgZW49T4KuzURXudKsNfjM4n0SYJwbiWUSzOqJJ3CWdXarFo82HARuYXa8gi7QiigV0U6VvLQbXp6RZLtDHE4xYW7TXmrilx7o77kePR1duqGehgys+ICJy8JW7YawSYCo9W4RolL6l5gDTMCSp1vk9vfXBWevngbWi5Px/O4Qhb3A+JfPiW/eTflNqTlcZRCi4YvYWpl3Dbfkl09HvBqAmpAGAKdFHOak63E6iiIB2E5Xlfew=
  # APP_CREDENTIALS_DEV_PWD
  - secure: r/KfwE+p+y6aQP5PjaWPZ0jEusCezUwUv/l3RK+1bevda85KNG0Kf8Sa8/DvjjL46pOryKNZCDRNQ9eu0EW9uyVepdVl2+i7GrB/0LA509zWpK+bg4TqHmC/0J8BDlgXfYfwzmYQn4KKt7FZMPPt2ua5Hk9IBe4iqJ5SniUx5+qKUwf5Jq1AzIe36Ko8QFNWU250stAxXUI5+aUnoEYEhmrA1KXj93d/YDTkPSOM9wKZ1CHfiTNG0fj/JCgxZ+r9KbQMTQnXgFOHlMj+tWXbdtP8t7h0FdkfqCZ57yMlU5s9pwAfzGKZS8Uc4FfMLGSPj4VpQ/1IG9S4dl7m/yvkTG9GyziZYA9QoH+oZlhs7RFosvndgEcBHiin4IsrZQgNPUNBVa0fMzUYKnkFifEw0hfqdh9P34g351DdIJ+H0jtyz2uC1IRM+6Bk0tr02gpfyko/ueqIcKzk7XWTbvnPC34PIidH8eCqQ2SaSOtkBT725CRMKKDpbZJBqGhur5BCD4vcxsBK8Lbr4hRtwkXTRXM3rAtpk3Rz6qtD9hGkyi2Q+QLJ70HQnkRuJ5Z+hHkui5w/5JZgfu5+aynpzbVXyzWT7b/01msilm+19i/NCBM5rl5Sb3VCF5hHmQDIhMLpgBFQ7iQXa+7KkRvB7MHJADan96ZTKJvfhzX3vNV9vPU=
  # APP_CREDENTIALS_STAGING_PWD
  - secure: HOUiwX4ZJ4q4YrKYpp6y/DGAI+YuO6AjDQ7oOcqvLqyx6sTpjSucLR0zpu1scVlq7yo1t+mmvI9BF/vBFkwVyEYJui5+CalgbIKwx5raXKMoG+lMlBPZLCMOSbThivRIgOWXvwRaxVe1KlMbkus4D36bdFhWfE0WBZEQxPkTcD3WF4qNJyoDlMmijOXZyMWcFn3RHYMwkfJkZv07dv1HDGna6YCv9mzVraZZNF/odPwHysSYfD/15FTFcLC1uNORMUiIqqSUKS3bwj/pVwwTyW6r3s5a2emRH8PZN1OtYB9BlDM3JS0i8f7l0dtebCCqYLvqk9ywCq4BJ5MtB40/tqx8AD/uwNqJRKXkjjeULAdQ5tYOtTD2d5BlKsEEsEr3qyHpMQDoXQtRSi1O9PG4vgowqbcLLMo2saRCVrUlRAckcd5bweOL36GfyKVh8E+M6vTqyUXEm25ZUrSxniLAU4yBuYlUE0LqnHUpgaDRFGpOZonI4raWo97a0Sq/hJiuoS2vf9L6gL3qElfbkL42lCbuakn5vKVFbYaUFhpPq8rT4roo8QFd8EVTqLqBXOb7mcYDjtD2Xv5WxmHROtR26rT/jXbJEeOVumizBlvc1sHx45XzJGUP5TJZvfLNrHwj3SX1CA60moKAxeqBSiqxu/ca4c8IvcbpeouFFROtk/s=
  # APP_CREDENTIALS_PROD_PWD
  - secure: O6jHZoO/X6nxEZfhXqLOidtT3HA+iWtAcIXssvzzAwGPzUFif0OQIW5/oxWvyWT1RpcXNzfGUTptKnkifxE4CRbGJvCf7MUYtvSTLMz4vblKtJJugdvLNfvC3KY2hCopdS1m2JNvRr6O7gZqFuIdxPA911WgNdSRzgP0IRHyuvQsQ3zqWK6UFCK6/W9TfIy85VQFEJcR5BSXnfsFmNGWUhfpmmmtMol5zNsafyhf2atBUyAHE7MN60nDJ3JR7s251DRBpPH1PDAtZAv5Js0CWAQiRyCfVDq/oyQFH9JPkD6Aanzq+3+qAxT3/UwXYd/fG+X4l4xsP1Re7iRPoWUS3eEdkg3LvgddPzhTTqCTeRExTbuyPHn4C1AoiNUDDcZPzw3mPC5/FQBqsiBc5v3TkQSwtr/WV4dihOUKpChn/IgFYlSdiy6gVJqZoKJqdRbJgWGcuJxJcvLCXeFNQ8dd3aK5oUAVGmqIcVHzVZuIdQgu7fOmL88wHSy/BdoMPQrYkUTu9v0e92SSfOMcP4uCpiFtSn67JAdFkkZIks+4ZJe35UZqeRNB0iF8/i1uvn/Y4erIuW9RtWYmCVExaOAax/P0cbRPaNELI6YLtPtHUwb1piNm2d6357H0U8xS66xpfUhYA1ao/+xiSKj7EyDHuUY3UafAlYLwcG1s7aRMb0w=
notifications:
  slack:
    secure: XdmOobsi4wzrlcJWjWis3zfdk04/y3sdgYk0U2O2P5owGFW4cJk3ZX0yFaTgxuM+hiWiN425Zd8RLGDNl9VaX5Gf4tWRGoNtNHUemUTg2FtT2wFH6Z+EBGLrjqcdy39rKrEIU7S5Z2xaUnrrgR0a7j7sJGe25dG9j4vhmbAl0wKBzxnZQUmD0/Zvd09tHOjh3fHnsVvkhGQvH9BcISDWU0jwYdvZV03FPVDY2fgF25rbinuYA3nkL21lodevJNCVrBF8WKWzRgLty0yuX/aSAMIAKM+XtZykPbMql2xLFO7B8lVjWmg0JoO7TayXaG5WQkaz3BlLg2olZFkpL4ar3hi2xAE84ChR0VYXt2weSLFl94jd6M/UeSINJoR8AaaS845T6xwfpSddzCTtZ6+Ts72wLfVN27J0yiDYViRHL9EP7EZOYdYYVvx0mNl24XWop2MmpWX0fWiJWpmPbhHH3Y7UomzMpQVjD+raoZIE0R6wwa5oVX2krooT0bEzo8VmdCrzgDO8YXFOy7krG0LFfoeJQwE5cYbodWebTydNzGL6z/qtCM1dFXl87Q9I61vhLa0XbttyLEALNimjEcrMW6boxLbuwxpuCX6RWHNP8JrZxNbxrFHjY9Oq1NRIb+z5oJ0ljLaBsaUymToEHXYrmB6RRVi15dBoklnSFo1ldq4=
  on_success: always
  on_failure: always
