matrix:
  include:
  - language: csharp
    dist: trusty
    sudo: required
    mono: none
    dotnet: 2.1
    script:
    - "./travis-build.sh --quiet verify"
    deploy:
    - provider: script
      script: "./deploy.sh dev"
      on: master
    - provider: script
      script: "./deploy.sh staging"
      on: staging
    - provider: script
      script: "./deploy.sh prod"
      on: production
    - provider: script
      skip_cleanup: true
      script: chmod +x ./travis-nuget-deploy.sh && ./travis-nuget-deploy.sh $NUGET_API_KEY
      on:
        all_branches: true
  - language: node_js
    node_js:
    - 10.8
    cache:
      directories:
      - "~/.npm"
      - "~/.cache"
      override:
      - npm ci
    before_script:
    - cd src
    - npm ci
    script:
    - npm test
    - cd ..
env:
  global:
  # APP_CREDENTIALS_DEV_PWD
  - secure: nlbGF3FYmKnt2f0QbID12dKQCsUds5hLjUKDQpXSwIlKoEmMJlSsiSSJliaMbi++AFGtkUcrClwlpd4XJT3SIZkh+WedIq4YjYpQ03h+eJF8+iEILavKct3XQZVFcHEAAKP0ENvFEzT+QfCJ8o9jV0gFYaUmrdJmbP/sFFkWx+lb+5pww3WdjtGK33depyPTVS1xyRavZ6hjOSCQxXfYqqwJUwukEhCAYB2cIjOtYtCId2sIAZ4ZcbEJGZy1dh0QeYnl2D7pQPTQbWholyBGwvfP9b8cmBxxdspIJuZn/hvjHQ/U7vzMv1GfmNEr+NEJbbCz4K4qtC9ZlnPF098TxapDFMN7FvywhSSI/WMQmVvUUn0P++D4UsHuNq71tH2G8YGudxF89VbhVMTTXz21o75mTj27YSvhSz5A5QJC3Cvz853aKvbTAmCL147CP6loqo1MuP6i9RWVUeUmMnUfqqHfpvvbc7uJAyjmSPEH5s/qTdkMRPW06VFIQPTgw1f95tOwq+s2uLDSRoRTTuDDZYLIsvL7rx4p3cxEsWDN3cXxIUqfa2BFtX8ZKNMCgjQ/0IQKxempOVvKLeW94uL/gpaZSxK0lUIg+U+L/fjyJkEb6syynuX/TtOHWNq4YxL2BHcu3w3ZKdoBSa7PGLZ9nLTwRMxSF5xTNPmoqJmjZ94=
  # APP_CREDENTIALS_STAGING_PWD
  - secure: niltxqkLffTERbnlgD1VhN0rdH0Pf45GylFA+ME3hs4XTLKUOpx1FT0QFPkxowqnqp1j7Z8JgzO6lphbs3B3pXjG6OnDS6wV+2JhTtpI8HO13xIh/RUc6M+xBn6e1blnfWlwKWhBYGxZtYOXO9wuceHbyPJptS3gE4LOOcdgj1f2aMCsjN0b1asuzepBUrrS17uVmTXEbB7mqLkoGG4T8hTSFWOuqM6WxfbxlX6NTl+Tce4udFkQ3vsb10TkFlhCe+5wAnMEA+I9XvVi31P+aC2JTwcWfDvNtPL9wyiPOk7c0RiP8isqAtGlX6PoqR+I94FwftC6uuSoWCVBUCkkWy5omkiws28SoBMbPulpTiZ3ydy1jg/hA2TR50RQHAx4www/Ga1GGJZemD6Yy+U3so4MHyoP44LsBIbUrQHDAQ58NfmWi13xf5uttKDi0zQIl7xEMENbHtxcEeihf5QFVeGEYbAZ8oDJiryKRvmqye0tEQ84frDB3DZmvec6CY2pzH9cyyu0XG3OwskD2ypBrJiasH/tU5zb7OL2gJ+P56yXrLAD4Us00JvrxnCmkQ9SF/Jje9wezGpapiZBVOA8E42jgyiZm+pdzCjNrOF9PuZzAfvPHzesMf4ywB1bR+oeJuE2YHDrZS0mo+DDGITY9iqG/dWywfUumRqAtnAckQg=
  # APP_CREDENTIALS_PROD_PWD
  - secure: hbI2Bd0ZBv/UfJ1z1whCLuFEZHUgeu4EW0DxX7bj23jXdstKyBn/KTL9IiZzi+h1YFeVjh2WLFPh1QY4t612jVgoFZUbJEVnO9jDu2P5NbpxH4lYnwRTl1bsTUO0tt8F2cYdOBHyjvPxUugBrSHjOT0lkQHpJEreIV9QkefXQZdX2qkBArIYo+ltGlRUJvp7m8zAWie8sXJjz5eLKEHgzGJ5wUZiMDwxXFwzhO9n26WnTO85jFOt/En3vT1Tgutgoq9o97lbhdtt4k97X5xop+1uXJcuZ+E2hc6yIl0Y/eSXSGupLFF5VhETn3L8DCmf8DBptTMyGuFHpFWqe5iYMYqWiAZKp3WhOrfWExSh9h+4kglhIDH6zhwdmmv3OJhXgwa8O1FafJyV9flFW5oTbWeL8UDNOR2NfINUZHLIsMfpZd+7YS+zSym67QomDNrR8bF8v3l+KMBYSNJIwgvFCF8vcllZmVIbvL8F87mWrOOgEWZ64c42pIshPyqa+0mBJdibbnFc7c+w/WsV+1NHBeooO/D+8dYMVr+VJisHWPrKk5Z3t79uzmsr//JMULD81dHIkBk1bbu219AubsE+A7FHkwpGWeqYkdinwYoNXKGjMKUs6VmpJF+OKwL6gv6o8MXNG7DQCII1JEHon+ASqSgktp5GU+3o5s+5sBha1nM=
  # NUGET_API_KEY
  - secure: j9isi8kQiNdMHGkXzvLzeT88erLNlhMB/ZJSK0XkG0L03j/iQpYplTqW/T8YwpkQgwnIj9Q+I9MfJdaduRyVotsZTtrEFKiikI6JKCUL4ORYoiOaQ0To2QXbFjRmnuc5+Pex+Ll/bBqQMZXtIFdUPy8jD4mSX6vJXkwsjzF1SJb+8cC8aKUs6fEGVgpL+ujOoVjY5Z6axQwzx36nYWO1LY5LmcoMGWt7bGb3d18QPg+fPq7ICctcYsLNtkbhsMVbTKXBws9vZkNr2Uu/yVcpY5/g4kE4rCJoPMHY4WoQoAh/hES0lTpCrCqIldrmO1p5TUkVE8A14vbUZgS0tGdfIlA9keFjgKARAkFojkyKGWhpZT7OVm52AkxoqhJMRBajhdkVa0Ust0YphJbPz7UDkY58UYUKGQBxgZkaFGhLGkEXAS77tOIDH1dFdX0BuQSF9uI8yyiP0+HD3I5JX7dH3ZOs4YWW9eQyzLGTXE/RQibTj+2gpHYUGRbgPc+he1zNKlTqdN9ahAw+npkopf1GDI6BmCxjJuCbTsf4hD9C6XW6pO0NRvOLFJFtaj8tqe4TySb57FwAD4F9qw/vpElsUFMdak56VkLgqjFRtTtvoZ36T2cjiOwPeLZoztafcDTB/dtPiRXUERxkE0THZdp5ogW9w7S/jJMPuvH91U93RZo=
notifications:
  slack:
    secure: XdmOobsi4wzrlcJWjWis3zfdk04/y3sdgYk0U2O2P5owGFW4cJk3ZX0yFaTgxuM+hiWiN425Zd8RLGDNl9VaX5Gf4tWRGoNtNHUemUTg2FtT2wFH6Z+EBGLrjqcdy39rKrEIU7S5Z2xaUnrrgR0a7j7sJGe25dG9j4vhmbAl0wKBzxnZQUmD0/Zvd09tHOjh3fHnsVvkhGQvH9BcISDWU0jwYdvZV03FPVDY2fgF25rbinuYA3nkL21lodevJNCVrBF8WKWzRgLty0yuX/aSAMIAKM+XtZykPbMql2xLFO7B8lVjWmg0JoO7TayXaG5WQkaz3BlLg2olZFkpL4ar3hi2xAE84ChR0VYXt2weSLFl94jd6M/UeSINJoR8AaaS845T6xwfpSddzCTtZ6+Ts72wLfVN27J0yiDYViRHL9EP7EZOYdYYVvx0mNl24XWop2MmpWX0fWiJWpmPbhHH3Y7UomzMpQVjD+raoZIE0R6wwa5oVX2krooT0bEzo8VmdCrzgDO8YXFOy7krG0LFfoeJQwE5cYbodWebTydNzGL6z/qtCM1dFXl87Q9I61vhLa0XbttyLEALNimjEcrMW6boxLbuwxpuCX6RWHNP8JrZxNbxrFHjY9Oq1NRIb+z5oJ0ljLaBsaUymToEHXYrmB6RRVi15dBoklnSFo1ldq4=
  on_success: always
  on_failure: always
