language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
env:
  global:
    - secure: "k+YW5hWXoyGDWwCCc9T7vzolGB/s/V865/fNe9nkZNNqFfBfglaDufmzM4Fn8FhFZsTqngD/x04ee5dB9uM3Kf0n6tvvDsrA9qMrsgIRLVNvL53T5K8u/C3d72cr23Axfg3RJySZOshoycRRXzTjk3Qa2HmiilKmhmowm30sV7TlaQ15fRdAUHzR7vrwh4IMLYp5NSYTN6ghP0XbVVulL23lv7qdjjOyOyWfan9sYRvWkVM4ZO9aJEXni9CXSY6pHFLsUVBMId4WDjPq1ZK5v9imeBdFY83UttD3tHb1zRg5HOdJ13HaEHHaeStUkDlv+8R7X8kIHPaZ1lGGM3VBu7+OADmon+2agSPorby7my7DSQ/aubReFLqN+f578jfnPPNpdDfEVmaxwlfoxYhHTdWUKUmBryFqJlJX2lJeB2scO/9EAA4l4ZY3/kCtBOpr88Bnv0yo6L38EiKc/TSd9VS8aoVg4Yt9orW6qMs5UUnhosMrsIrqqYmMnhzshduIHIoEGCjOp3+/RWWP9rQcZdnpwQzkCZXq9T7iv9bcmlqpv1VN/Lg4NUrRW/xkb74c6U255Fm8EGYGUzWFLeJM1MsjMR+5SH7NVnjCJEmUlwMim+RSgUJIRt3uXBjZi906S8ZMJdpEdktnnbQzqBtyVuHwAvQHQjUpjNqsPAUPGTk="
    - secure: "cBGPEz6pvrLiEaZ3Qe6mrXBjYxL+TVqXxZL7yIV3s56iRTTFjt22puQMDrQZdZ/SVDkxD27eP0rgWRRCrrTMLLaJ0+C7LY5JZOX7gFMYapVTRLiCX+raoNqD9v7xdr+4/W1IECNcFXNaNv3T/E3JEh9NN8oicBTjX7+lqp/3F3KKsgSgZpWMLCf2cuuxPALqjHKfISojtIcumaTK/okK95uaFTXRGPujKdSRq6xOTVp2si9ukRKU+81Nt58IOgxvN1d+LBwZ2KotdyPmFoHz/v/0cBry068t6z+3HFE1p/i5gEJMyy0AramNZ1gPdSeHvMYXdJ2/5LSw86+TmG88jLE23vsKlpcE1mVmc++QZe7vzMHoCIF7RqwTXlVyAVFSujOu6TUCfWHpzf7Oy/dVruHOAqK+0sdw4oULab/EShrdpKJIirlSUfVH1YPDfyhY8Px6MPBurY1lgWQUWKCaIf1jlu3GFBfTEJOiLRN63HmoVmD7DD04dKsGCfSqpwfRJoSHuFL+aRjxlUfK5186AvlxMpp9uuctzufKVXKMXADJGUaLYYAAS6LMNmjEmMintNpzw0w/zSfKtw4h6hbW0SPXHZ4pjSvm+K4QCSjeyXU0s2KHWGujAU7HsBDjcKYQGqzRCIUSojeIaJ+RQg51Ed/VB8Q1Fxk3adbW1HK7fMo="
    - secure: "MEPPOLuro+9Tz3wFmhoBR9degSTJUlJdo8rMe8Il7kYoMxewj9NpfRKUh9sLDi626b1EDcO84a7sBroyXYirJP0OUVI7uo6/EG47FxiDFmOcKq2/E5LMmcYjAWmQuEuA+kiGRDc3OTvLMui6e1Iq3kjN0L0TEH+Vgy32xusLyo8bmWSa7VRXtABuJkpPIT+bGdaNpTOAX7kxPEdRgeQdZ5l5TTMQ0VFpocfj9i2uG49I0f62MPBvIditwSRzKjtHFJ3xog1/qEusq5nEdbJX7trqUUt6I5GGHLujsCx2y8/oudqNNja40RmE4g/egp+AJ5qC9CZCkiRMJBdHHZWZ16E3fh2vP9Vnb74MrNKbpGkFl58ufGJ1IV1S2iV2PPCI1GD6Az7vlucMDOtwFKFQsoQ9gf1zK4g9wqfmhLN6jH2S3pt8rQIU6oUYXNnZVnbRToue2xh28RitM7lztgYgLPngGWvuAuaDnGzGJFx9+iBZk1QM+iAnl9MtW9UhrfwRl2UJAoVMyOY8oCFqOhUmM0dnU0vFLQ/gFrjYu6JnWeOYPFAaTVrEdwX3PYpnDb+x5C75kJp2E+icOo3jegpEjTLaLVgfrPpZaCryET0o7lER+lwroB7g1XZMgRKnP6JBrsrFJwtzfIh6IYYieHd9JRGd9x/qRMV527EitsVEOCk="
script:
- "./travis-build.sh --quiet verify"
branches:
  only:
  - master
  - staging
  - production
deploy:
  - provider: azure_web_apps
    username: travis-deploy-user
    site: as-de-bat-ui
    on:
      branch: master
  - provider: azure_web_apps
    username: travis-deploy-user
    site: as-te-bat-ui
    on:
      branch: staging
  - provider: script
    script: bash travis-deploy.sh $OC_WEBHOOK_DEV
    on:
      branch: master
  - provider: script
    script: bash travis-deploy.sh $OC_WEBHOOK_STAG
    on:
      branch: staging
  - provider: script
    script: bash travis-deploy.sh $OC_WEBHOOK_PROD
    on:
      branch: production
